
/*dce-form-step.min.js*/
;function dce_show_step(target,element,direction='next',scroll=!1){var form=jQuery('.elementor-element-'+element);var step=jQuery('.elementor-element-'+element+' #dce-form-step-'+target);jQuery('.elementor-element-'+element+' .elementor-error').removeClass('elementor-error');jQuery('.elementor-element-'+element+' .dce-form-step').hide().addClass('elementor-hidden');jQuery('.elementor-element-'+element+' .dce-step-active').removeClass('dce-step-active');jQuery('.elementor-element-'+element+' .dce-step-active-progressbar').removeClass('dce-step-active-progressbar');jQuery('.elementor-element-'+element+' #dce-form-step-'+target+'-progressbar').addClass('dce-step-active-progressbar');jQuery('.elementor-element-'+element+' .dce-step-active-summary').removeClass('dce-step-active-summary');jQuery('.elementor-element-'+element+' #dce-form-step-'+target+'-summary').addClass('dce-step-active-summary');jQuery('.elementor-element-'+element+' #dce-form-step-'+target+'-summary').addClass('dce-step-filled-summary');if(!jQuery('.elementor-element-'+element+' .dce-form-step-summary').not('.dce-step-filled-summary').length){jQuery('.elementor-element-'+element+' .dce-form-summary-wrapper .elementor-button-wrapper').show()}
if(step.hasClass('dce-form-visibility-step')){if((step.hasClass('dce-form-visibility-step-hide-init')&&!step.hasClass('dce-form-visibility-step-hide'))||(step.hasClass('dce-form-visibility-step-show-init')&&!step.hasClass('dce-form-visibility-step-show'))){dce_epro_applyStep(direction,step);console.log('skip step '+target+', direction '+direction);var new_target=step.find('.elementor-button-'+direction).attr('data-target');return dce_show_step(new_target,element,direction,scroll)}}
console.log('apply step '+target);dce_epro_applyStep(direction,step);console.log('show step '+target);step.css('display','flex').addClass('dce-step-active');step.removeClass('elementor-hidden');if(scroll){console.log('scroll to top');jQuery('html, body').animate({scrollTop:jQuery('.elementor-element-'+element).offset().top},500)}
return!0}
function dce_epro_applyStep(direction,step){if(direction=='next'){step_direction=step.prev()}else{step_direction=step.next()}
if(step_direction){console.log('applyStep '+step_direction.attr('id'));if(step_direction.find('.e-form__buttons__wrapper__button-'+direction).length){console.log('epro click');step_direction.find('.e-form__buttons__wrapper__button-'+direction).trigger('click');return!0}}
return!1}
function dce_valid_step(step){}
function dce_validate_step(step){var isValid=!0;step.find('.elementor-field-group [required]').each(function(index,el){if(!el.checkValidity()){el.reportValidity();return isValid=!1}});return isValid}
function dce_replace_field_shortcode(target,element,direction='next'){}
function dce_form_field_custom_id(type,id){var tmp=id.split('-');switch(type){case 'checkbox':case 'radio':tmp.pop();default:return tmp.pop()}
return id}
/*dce-form-summary.min.js*/
;(function($){var WidgetElements_FormHandler=function($scope,$){var elementSettings=get_Dyncontel_ElementSettings($scope);var id_scope=$scope.attr('data-id');var summary=elementSettings.dce_step_summary;if(summary){$scope.find('input, textarea, select').on('change',function(){var custom_id=jQuery(this).attr('name').replace("form_fields[","").replace("[","").replace("]","").replace("]","").replace("[]","");var input_type=jQuery(this).attr('type')?jQuery(this).attr('type'):jQuery(this).prop("tagName");var input_value='';switch(input_type){case 'radio':input_value=jQuery('.elementor-element-'+id_scope+' input[id^="form-field-'+custom_id+'-"]:checked').val();break;case 'checkbox':input_value=jQuery('.elementor-element-'+id_scope+' input[id^="form-field-'+custom_id+'-"]:checked').map(function(){return jQuery(this).val()}).get();if(input_value){input_value=input_value.join(', ')}
break;case 'select':input_value=jQuery(this).val();input_value=jQuery('.elementor-element-'+id_scope+' input[id="form-field-'+custom_id+'"] option:selected"').text()
break;case 'textarea':input_value=jQuery(this).val();if(input_value.length>20){input_value=input_value.substr(0,20);input_value+='...'}
break;default:input_value=jQuery(this).val()}
jQuery('.elementor-element-'+id_scope+' span[id="dce-summary-value-form-field-'+custom_id+'-'+id_scope+'"]').text(input_value);setTimeout(function(){jQuery('.elementor-element-'+id_scope+' .dce-form-step.dce-form-visibility-step').each(function(){var step=jQuery(this);var step_id=step.attr('data-custom_id');var step_summary=jQuery('.elementor-element-'+id_scope+' #dce-form-step-'+step_id+'-summary');if(step.hasClass('dce-form-visibility-step-show-init')){if(step.hasClass('dce-form-visibility-step-show')){step_summary.show()}else{step_summary.hide()}}
if(step.hasClass('dce-form-visibility-step-hide-init')){if(step.hasClass('dce-form-visibility-step-hide')){step_summary.hide()}else{step_summary.show()}}});jQuery('.elementor-element-'+id_scope+' *[name^="form_fields"]').each(function(){var custom_id=jQuery(this).attr('name').replace("form_fields[","").replace("[","").replace("]","").replace("]","").replace("[]","");if(jQuery(this).prop('disabled')){jQuery('.elementor-element-'+id_scope+' #dce-summary-form-field-'+custom_id).hide()}else{jQuery('.elementor-element-'+id_scope+' #dce-summary-form-field-'+custom_id).show()}})},100)});$scope.on('click','.dce-form-step-summary-edit',function(){var step_id=jQuery(this).attr('data-target');var element_id=jQuery(this).attr('data-element');dce_show_step(step_id,element_id)});$scope.on('click','.dce-form-summary-wrapper .elementor-button-submit',function(){$scope.find('.dce-form-summary-wrapper').slideUp();$scope.find('.elementor-field-type-submit button').trigger('click')})}};$(window).on('elementor/frontend/init',function(){elementorFrontend.hooks.addAction('frontend/element_ready/form.default',WidgetElements_FormHandler)})})(jQuery)
/*dce-settings.min.js*/
;function get_Dyncontel_ElementSettings($element){var elementSettings=[];var modelCID=$element.data('model-cid');if(elementorFrontend.isEditMode()&&modelCID){var settings=elementorFrontend.config.elements.data[modelCID];var type=settings.attributes.widgetType||settings.attributes.elType;var settingsKeys=elementorFrontend.config.elements.keys[type];if(!settingsKeys){settingsKeys=elementorFrontend.config.elements.keys[type]=[];jQuery.each(settings.controls,function(name,control){if(control.frontend_available){settingsKeys.push(name)}})}
jQuery.each(settings.getActiveControls(),function(controlKey){if(-1!==settingsKeys.indexOf(controlKey)){elementSettings[controlKey]=settings.attributes[controlKey]}})}else{elementSettings=$element.data('settings')||{}}
return elementSettings}(function($){var get_Dyncontel_ElementSettings=function($element){var elementSettings={};var modelCID=$element.data('model-cid');if(elementorFrontend.isEditMode()&&modelCID){var settings=elementorFrontend.config.elements.data[modelCID];var settingsKeys=elementorFrontend.config.elements.keys[settings.attributes.widgetType||settings.attributes.elType];var type=settings.attributes.widgetType||settings.attributes.elType;if(!settingsKeys){settingsKeys=elementorFrontend.config.elements.keys[type]=[];jQuery.each(settings.controls,function(name,control){if(control.frontend_available){settingsKeys.push(name)}})}
jQuery.each(settings.getActiveControls(),function(controlKey){if(-1!==settingsKeys.indexOf(controlKey)){elementSettings[controlKey]=settings.attributes[controlKey]}})}else{elementSettings=$element.data('settings')||[]}
return elementSettings}})(jQuery)
/*main.min.js*/
;(function($){$(window).on('elementor/frontend/init',function(){if(elementorFrontend.isEditMode()){elementor.channels.editor.on('dceMain:previewPage',function(e,editor){var model=e.getOption('editedElementView').getEditModel(),currentElementType=model.get('elType')})}})})(jQuery)